import Head from 'next/head'

/**
 * Home page.
 *
 * @returns {HTMLElement} - Home page.
 */
export default function Home () {
  return (
    <>
      <Head>
        <title>Allel Elektrokonsult AB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <h1>Allel Elektrokonsult AB</h1>
      <h3>Projektering</h3>
      <p>Vi projekterar och har erfarenhet av det mesta nyproduktion som ombyggnad till renoveringar. Allt från enklare "pekjobb" till hela bostadskvarter, skolor, badanläggningar, idrottsanläggningar. Vi räds inget och glädjer oss åt nya utmaningar!</p>
      <h3>Kostnadseffektiv</h3>
      <p>Tack vare vår platta organisation, högpresterande personal med bred kompetens och minimala omkostnader kan vi erbjuda ett av marknadens bästa priser på våra tjänster!</p>
      <h3>Kontrolluppdrag</h3>
      <p>Vi har lång erfarenhet av kontrolluppdrag och elbesiktningar. Alla typer av entreprenader och även projekteringar kan vi ha kontroll över. Vi utför både förbesiktningar och slutbesiktningar och levererar enkla och tydliga protokoll. Vi kan granska fakturor och äta-arbeten, vi vet vad saker ska kosta!</p>
    </>
  )
}
